### ISSUE TITLE
Does this Widget work for web?

### ISSUE THREAD

**Issue by EriKWDev** [rithik-dev/google_maps_widget#12]
When I try to compile for web, I simply get "TargetPlatform is not yet supported" in place of the map when I visit the web page.

I have added the link with my API key inside web/index.html as it says in the README.

On pub.dev it says that web is supported by this plugin. What's the status?

**Comment by rithik-dev** [comment]
Hey, the package is just a wrapper around the official google_maps_flutter package by flutter, and the underlying package does not support web.

So, currently, this package also does not support web. I'll update the README to fix this...

**Comment by rithik-dev** [comment]
Hey, @EriKWDev , I've updated the README in reference to this issue.

I'm closing this PR for now, feel free to re-open this issue if you need more help..
