### ISSUE TITLE
Ability to Rotate car to Path Direction

### ISSUE THREAD

**Issue by ShivamMattoo33** [rithik-dev/google_maps_widget#5]
Hello,
I am trying to implement a tracker service and I want the car marker to point towards the road it headed to. Upon doing some research I would want the rotate parameter in the Marker for at least driverMarkerIconInfo unless you recommend any other way?
Thanks

**Comment by rithik-dev** [comment]
Sure, will add the "rotation" and "anchor" properties to the marker icon info class.

Thanks for reporting this issue.

**Comment by rithik-dev** [comment]
Hi @ShivamMattoo33, the fix is live. Try using version [1.0.3](https://pub.dev/packages/google_maps_widget) and it should work fine.

Thanks for reporting this issue.
