### ISSUE TITLE
Dynamic polylines

### ISSUE THREAD

**Issue by ShivamMattoo33** [rithik-dev/google_maps_widget#7]
Hello,
I want the polylines to be generated on the map dynamically based on drivers position and  a fixed destination. So basically as driver moves closer to destination previous lines disappear as it has a new source location
I am getting stream of driver latitude and longitude from the api. How do I set a dynamic source location or what is the best possible way to handle this?
Thanks

**Comment by ShivamMattoo33** [comment]
Hi Any updates on this ?

**Comment by rithik-dev** [comment]
Hey, I was thinking of providing a boolean named updatePolylinesOnDriverLocUpdate, that will call the polylines API whenever a new stream element to the driver stream is pushed, and update the polylines. (from the driver to the destination)

Let me know if that'll work for you..

@ShivamMattoo33

**Comment by ShivamMattoo33** [comment]
That will work worth giving a try. Having these things sorted out which makes this widget compatible with real world use cases like updated polylines and rotation of cars on turns would make this package super popular and useful

**Comment by rithik-dev** [comment]
Hi @ShivamMattoo33, the fix is live. Try using version [1.0.4](https://pub.dev/packages/google_maps_widget/versions/1.0.4) and it should work fine.

Thanks for reporting this issue.

**Comment by ShivamMattoo33** [comment]
That worked like a charm Thanks

**Comment by rithik-dev** [comment]
That is great to hear!!

However, I was thinking to default the value to false, (right now it's true), as not everyone would want that in my opinion.

Just make sure to explicitly assign true to the variable updatePolylinesOnDriverLocUpdate, so even if I change the default value in the future, you code doesn't break.

Thanks

**Comment by ShivamMattoo33** [comment]
Yes that works
